security:
    providers:
        cache_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            stateless: true
            provider: cache_user_provider
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
    access_control:
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
